####################################################
##    Settings for gathering resources from trees
####################################################

##    All Times in Seconds    ##

RespawnTime: 5
Alerts:
  AlertFinds: true
    Message: "Your efforts in mining were rewarded with {R}!"
  AlertDeplete: true
    Message: "This Watermelon node is depleted! Come back later!"
Drops:
  DropsList: [NETHER_WART, NETHERRACK, SOULSAND]
  DropChances: [1, 19, 80]
  DropCounts: [1, 1, 1, 2]
Experience: 5
